<!DOCTYPE html>
<html>
    <head>
        <link href="../css/jquery-ui-1.9.0.custom.css" type="text/css" rel="stylesheet"></link>
        <script src="../js/jquery-1.8.2.js" type="text/javascript"></script>
        <script src="../js/jquery-ui-1.9.0.custom.js" type="text/javascript"></script>
        <link rel="stylesheet" type="text/css" media="screen" href="../js/jqgrid/css/ui.jqgrid.css" />
        <script src="../js/jqgrid/js/i18n/grid.locale-es.js" type="text/javascript"></script>
        <script src="../js/jqgrid/js/jquery.jqGrid.min.js" type="text/javascript"></script>
        <script src="../js/index.js" type="text/javascript"></script>
        <meta charset="utf-8"/>
        <title>Problema04</title>
    </head>
    <body>
        <h4>Problema04</h4>
        <table cellpadding="0" cellspacing="0">
            <tr>
                <td>
                    <table id="divTabla">
                    </table>
                    <div id="divPieTabla">
                    </div>
                </td>
            </tr>
        </table>


        <div id="dvRegistro" style="display: none">
            <table cellpadding="2" cellspacing="0" style="width: 450px;">
                <colgroup>
                    <col width="30%" />
                    <col width="70%" />
                </colgroup>
                <tr>
                    <td colspan="2">
                    </td>
                </tr>
                <tr>
                    <td>
                        Name:
                    </td>
                    <td>
                        <input type="text" id="txtName">
                    </td>
                </tr>
                <tr>
                    <td>
                        Email:
                    </td>
                    <td>
                        <input type="text" id="txtEmail">
                    </td>
                </tr>
                <tr>
                    <td>
                        Phone:
                    </td>
                    <td>
                        <input type="text" id="txtPhone">
                    </td>
                </tr>
                <tr>
                    <td>
                        Address:
                    </td>
                    <td>
                        <input type="text" id="txtAddress">
                    </td>
                </tr>
                <tr>
                    <td>
                        Position:
                    </td>
                    <td>
                        <input type="text" id="txtPosition">
                    </td>
                </tr>
                <tr>
                    <td>
                        Salary:
                    </td>
                    <td>
                        <input type="text" id="txtSalary">
                    </td>
                </tr>
                <tr>
                    <td>
                        skills:
                    </td>
                    <td>
                        <select id="ddlskills">
                        </select>
                    </td>
                </tr>
            </table>
        </div>
    </body>
</html>
